server:
  port: 8999
  
 

eureka:
  instance:
    hostname: localhost
    
     

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: user_service
        uri: lb://user_service
        predicates:
        - path=/user/**
      - id: constact_service
        uri: lb://constact_service
        predicates:
        - path=/contact/**
 
  
 
  

    
